=begin
#Signing Today Web

#*Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter. 

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SigningTodayAPIClient::Bit4idPathgroupNotificationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'Bit4idPathgroupNotificationsApi' do
  before do
    # run before each test
    @api_instance = SigningTodayAPIClient::Bit4idPathgroupNotificationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Bit4idPathgroupNotificationsApi' do
    it 'should create an instance of Bit4idPathgroupNotificationsApi' do
      expect(@api_instance).to be_instance_of(SigningTodayAPIClient::Bit4idPathgroupNotificationsApi)
    end
  end

  # unit tests for notifications_dst_id_delete
  # Clear Notifications for a DST
  # This API notifies that a user consumed all active notifications for a DST.
  # @param id The value of _the unique id_
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'notifications_dst_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for notifications_dsts_get
  # Get latest DST Notifications
  # This APIs allows to get latest user Notifications for DSTs sorted desc by time.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :top A number of results to return. Applied after **$skip** 
  # @option opts [Integer] :skip An offset into the collection of results
  # @option opts [Boolean] :count If true, the server includes the count of all the items in the response 
  # @return [NotificationsResponse]
  describe 'notifications_dsts_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for notifications_push_token_delete
  # Clear a registered push notification token
  # This API deregister a deviceId from the push notifications.
  # @param device_id The _deviceId_ to deregister
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'notifications_push_token_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for notifications_push_token_post
  # Register a token for push notifications
  # This API allows to register a token for push notifications. Only trusted deviceId can be registered. 
  # @param inline_object6 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'notifications_push_token_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
