=begin
#Signing Today Web

#*Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter. 

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SigningTodayAPIClient::RobotApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RobotApi' do
  before do
    # run before each test
    @api_instance = SigningTodayAPIClient::RobotApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RobotApi' do
    it 'should create an instance of RobotApi' do
      expect(@api_instance).to be_instance_of(SigningTodayAPIClient::RobotApi)
    end
  end

  # unit tests for robot_configuration_put
  # Edit the Robot configuration
  # This API allows to edit the Robot configuration. 
  # @param robot_configuration RobotConfiguration.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :username The _username_ associated to the account
  # @option opts [String] :domain The _domain_ associated to the account
  # @return [nil]
  describe 'robot_configuration_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
