=begin
#Signing Today Web

#*Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter. 

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SigningTodayAPIClient::SigningServicesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SigningServicesApi' do
  before do
    # run before each test
    @api_instance = SigningTodayAPIClient::SigningServicesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SigningServicesApi' do
    it 'should create an instance of SigningServicesApi' do
      expect(@api_instance).to be_instance_of(SigningTodayAPIClient::SigningServicesApi)
    end
  end

  # unit tests for sign_service_open
  # sign-service open post
  # description bla bla
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'sign_service_open test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sign_service_open_id
  # sign-service-open-transaction-id post
  # @param transaction_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'sign_service_open_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for signature_id_perform_id_post
  # sign-service-signature-id-perform-identity-id post
  # @param signature_id 
  # @param identity_id 
  # @param [Hash] opts the optional parameters
  # @option opts [InlineObject8] :inline_object8 
  # @return [Object]
  describe 'signature_id_perform_id_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
