=begin
#Signing Today Web

#*Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter. 

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3

=end

require 'date'

module SigningTodayAPIClient
  class IdentityProviderDataTokenInfo
    attr_accessor :ul_min_pin_len

    attr_accessor :manufacturer_id

    attr_accessor :ul_free_public_memory

    attr_accessor :serial_number

    attr_accessor :ul_total_public_memory

    attr_accessor :label

    attr_accessor :flags

    attr_accessor :ul_total_private_memory

    attr_accessor :model

    attr_accessor :ul_free_private_memory

    attr_accessor :ul_max_pin_len

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'ul_min_pin_len' => :'ulMinPinLen',
        :'manufacturer_id' => :'manufacturerID',
        :'ul_free_public_memory' => :'ulFreePublicMemory',
        :'serial_number' => :'serialNumber',
        :'ul_total_public_memory' => :'ulTotalPublicMemory',
        :'label' => :'label',
        :'flags' => :'flags',
        :'ul_total_private_memory' => :'ulTotalPrivateMemory',
        :'model' => :'model',
        :'ul_free_private_memory' => :'ulFreePrivateMemory',
        :'ul_max_pin_len' => :'ulMaxPinLen'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'ul_min_pin_len' => :'Float',
        :'manufacturer_id' => :'String',
        :'ul_free_public_memory' => :'Float',
        :'serial_number' => :'String',
        :'ul_total_public_memory' => :'Float',
        :'label' => :'String',
        :'flags' => :'Float',
        :'ul_total_private_memory' => :'Float',
        :'model' => :'String',
        :'ul_free_private_memory' => :'Float',
        :'ul_max_pin_len' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SigningTodayAPIClient::IdentityProviderDataTokenInfo` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SigningTodayAPIClient::IdentityProviderDataTokenInfo`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'ul_min_pin_len')
        self.ul_min_pin_len = attributes[:'ul_min_pin_len']
      end

      if attributes.key?(:'manufacturer_id')
        self.manufacturer_id = attributes[:'manufacturer_id']
      end

      if attributes.key?(:'ul_free_public_memory')
        self.ul_free_public_memory = attributes[:'ul_free_public_memory']
      end

      if attributes.key?(:'serial_number')
        self.serial_number = attributes[:'serial_number']
      end

      if attributes.key?(:'ul_total_public_memory')
        self.ul_total_public_memory = attributes[:'ul_total_public_memory']
      end

      if attributes.key?(:'label')
        self.label = attributes[:'label']
      end

      if attributes.key?(:'flags')
        self.flags = attributes[:'flags']
      end

      if attributes.key?(:'ul_total_private_memory')
        self.ul_total_private_memory = attributes[:'ul_total_private_memory']
      end

      if attributes.key?(:'model')
        self.model = attributes[:'model']
      end

      if attributes.key?(:'ul_free_private_memory')
        self.ul_free_private_memory = attributes[:'ul_free_private_memory']
      end

      if attributes.key?(:'ul_max_pin_len')
        self.ul_max_pin_len = attributes[:'ul_max_pin_len']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          ul_min_pin_len == o.ul_min_pin_len &&
          manufacturer_id == o.manufacturer_id &&
          ul_free_public_memory == o.ul_free_public_memory &&
          serial_number == o.serial_number &&
          ul_total_public_memory == o.ul_total_public_memory &&
          label == o.label &&
          flags == o.flags &&
          ul_total_private_memory == o.ul_total_private_memory &&
          model == o.model &&
          ul_free_private_memory == o.ul_free_private_memory &&
          ul_max_pin_len == o.ul_max_pin_len
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [ul_min_pin_len, manufacturer_id, ul_free_public_memory, serial_number, ul_total_public_memory, label, flags, ul_total_private_memory, model, ul_free_private_memory, ul_max_pin_len].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        SigningTodayAPIClient.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end
        
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
